### ISSUE TITLE
Panel switch is not working when top Navigation is in use.

### ISSUE THREAD

**Issue by tok3** [bezhanSalleh/filament-panel-switch#12]
### What happened?

When topNavigation() is enabled in the panel provider, the switcher becomes unclickable.

### How to reproduce the bug

Enable topNavigation()  in the panel provider. Switch to the panel in which navigation is set to topNavigation(), then try to switch to another panel using panel switch.

### Package Version

1.0.1

### PHP Version

8.1

### Laravel Version

10.26.2

**Comment by bezhanSalleh** [comment]
Use another appropriate render hook.

**Comment by tiagof** [comment]
Having the same issue and the render hook makes no difference.

It seems that when a panel uses `->topNavigation()`, although the Panel Switch button is there (wherever you hook it to), clicking it does not show the panel selection modal.
