### ISSUE TITLE
[Bug]: Slide-Over design doesn't work

### ISSUE THREAD

**Issue by wq9578** [bezhanSalleh/filament-panel-switch#19]
### What happened?

The default design appears. (All other designs work.)

### How to reproduce the bug

Specify `$panelSwitch->slideOver();` as instructed [here](https://filamentphp.com/plugins/bezhansalleh-panel-switch#slide-over).

### Package Version

1.0.4

### PHP Version

8.2.5

### Laravel Version

10.39.0

### Which operating systems does with happen with?

macOS

**Comment by wq9578** [comment]
Works now. Probably my mistake, sorry.

**Comment by RC-CTO** [comment]
If anyone comes here in the future, the solution is to set a smaller modal size. If you leave the modal full size, it wont slide over since its the full screen. Works as intended but hard to figure out.
