### ISSUE TITLE
[Question]: How can I only display panels that I have access to

### ISSUE THREAD

**Issue by mstfkhazaal** [bezhanSalleh/filament-panel-switch#22]
### What happened?

How can I only display panels that I have access to

### How to reproduce the bug

i try this but not work
->visible(fn (): bool => auth()->user()?->hasAnyRole([
            'admin',
            'general_manager',
            'super_admin',
        ]));

### Package Version

1.0.5

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS

**Comment by bezhanSalleh** [comment]
use the `exclude()` method it also accepts a closure
