### ISSUE TITLE
[Bug]: Conflict with pennant if panels have Feature

### ISSUE THREAD

**Issue by kiwina** [bezhanSalleh/filament-panel-switch#28]
### What happened?

cannot run migrations

### How to reproduce the bug

add Feature to a panel file

### Package Version

1.0.5

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Linux

### Notes

```
if (!app()->runningInConsole()) {}
```
fixes the issue

**Comment by bezhanSalleh** [comment]
shouldn't be a problem with the plugin but filament itself. if you could submit repro pro i will have a better understanding of the issue and then a fix would be easy.
