### ISSUE TITLE
[Bug]: Panel Switcher Does Not Update Panel Title in SPA Mode

### ISSUE THREAD

**Issue by onairmarc** [bezhanSalleh/filament-panel-switch#30]
### What happened?

When Filament is in SPA Mode, switching panels does not update the label to the newly selected panel in simple mode.

### How to reproduce the bug

Enable Filament SPA Mode and then select a different panel.

### Package Version

1.0.6

### PHP Version

8.3

### Laravel Version

11.20

### Which operating systems does with happen with?

macOS, Linux

### Notes

Previously, switching panels triggered a full-page refresh which in turn caused the new panel name to display properly. Now that the full-page refresh to the new panel does not happen, the new panel name is not reflected in the panel switcher. Instead, the first panel loaded on the initial page render is displayed.

For example, if Filament is loaded first in Panel A and then I switch to Panel B, Panel A remains in the label. Without any code changes, if Filament is loaded first in Panel B and then I switch to Panel A, Panel B remains in the label.

**Comment by bezhanSalleh** [comment]
Admin panels in spa mode 🤔 never done it. No plans atm. You are welcome to to PR a fix
