### ISSUE TITLE
[Bug]: TypeError PHP 8.3.9 11.27.2 Illuminate\Filesystem\Filesystem::{closure}(): Argument #1 ($panel) must be of type Filament\Panel, string given, called in C:\laragon\www\zzzwebsitename\storage\framework\views\892a0b716954acac6a4efb6fdfdc9b0e.php on line 158

### ISSUE THREAD

**Issue by arturodacostasoler** [bezhanSalleh/filament-panel-switch#36]
### What happened?

When I installed

composer require bezhansalleh/filament-panel-switch

The following error appears:

[Bug]: TypeError PHP 8.3.9 11.27.2 Illuminate\Filesystem\Filesystem::{closure}(): Argument #1 ($panel) must be of type Filament\Panel, string given, called in C:\laragon\www\zzzwebsitename\storage\framework\views\892a0b716954acac6a4efb6fdfdc9b0e.php on line 158

I have to run the follwing command to remove it and the error dissapears:

composer remove bezhansalleh/filament-panel-switch

I'm using filament multitenancy.

### How to reproduce the bug

When I installed

composer require bezhansalleh/filament-panel-switch

The following error appears:

[Bug]: TypeError PHP 8.3.9 11.27.2 Illuminate\Filesystem\Filesystem::{closure}(): Argument #1 ($panel) must be of type Filament\Panel, string given, called in C:\laragon\www\zzzwebsitename\storage\framework\views\892a0b716954acac6a4efb6fdfdc9b0e.php on line 158

I have to run the follwing command to remove it and the error dissapears:

composer remove bezhansalleh/filament-panel-switch

I'm using filament multitenancy.

### Package Version

1.0.7

### PHP Version

8.3.9

### Laravel Version

11.27.2

### Which operating systems does with happen with?

Windows

### Notes

I have to run the follwing command to remove it and the error dissapears:

composer remove bezhansalleh/filament-panel-switch

I'm using filament multitenancy.

**Comment by arturodacostasoler** [comment]
The Previous version 3.x-dev 521f2e0 was working fine.

It started failing when the follwing updrade occurred (I can read that I was using version 3.x-dev 521f2e0 at that time):

Upgrading bezhansalleh/filament-panel-switch (3.x-dev 521f2e0 => 3.x-dev 0426968): Extracting archive

Something changed from version 3.x-dev 521f2e0 to version 3.x-dev 0426968 that triggered that Error.

My best regards and hopes for this to be fixed to be able to use again this great Filament Plugin Package.

With respect and appreciation.

Engineer Arturo Antonio DaCosta Soler

**Comment by bezhanSalleh** [comment]
Seems, like you might have published the plugin's view in your previous installation. if that's the case and you have customized the view then republish the view and adjust your customization.
```
php artisan vendor:publish --tag="filament-panel-switch-views" --force
```

otherwise let me know.

**Comment by arturodacostasoler** [comment]
The code line you provided worked fine:

php artisan vendor:publish --tag="filament-panel-switch-views" --force

Thank You Very Much.

My Best Regards.

:)
